update

diff --git a/databases/database_drop b/databases/database_drop
--- a/databases/database_drop
+++ b/databases/database_drop
@@ -3,23 +3,31 @@
 
 ###this functions check if database exit or not
 urls=mydatabase
-check()
-{
-    regex="^[a-zA-Z#]{0,100}$" 
-     if [[ $1 =~ $regex ]]
-      then 
-          if [[ -d $urls/$1  && ! -z $urls/$1 ]]
-            then
-            rm -r $urls/$1  2>> error.log 
-            
-          else
-            echo "database is Not Exit"
-          fi
+check() {
+  
+  if [[ `check_name $1` = 'true' ]]; then
+    if [[ -e "$urls/$1" ]]; then
+
+      read -p "Are you sure ? [Y/N or y/n] : " flag
+      if [[ $flag = @([Yy]) ]]; then
+        rm -r $urls/$1 2>>./.error.log
+        if [[ $? == 0 ]]; then
+          echo "Database Dropped Successfully"
+        else
+          echo " no changes "
+        fi
       else
-          echo "Invild name of database"       
+        echo " no changes "
+
       fi
+    else
+      echo "Database Not found"
+    fi
+
+  else
+    echo "Invild name of database"
+  fi
 }
-      
-     
+
 read -p "Enter your database to Drop :" database_name
 check $database_name
